apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: app-ui
spec:
  replicas: {{ .Values.application.replicas.ui }}
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: {{ print "ghcr.io/datalens-tech/datalens-ui:" .Values.application.versions.ui }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_INSTALLATION
              value: opensource
            - name: APP_ENV
              value: production
            - name: APP_MODE
              value: full
            - name: AUTH_POLICY
              value: disabled
            - name: US_ENDPOINT
              value: http://us-cip:8080
            - name: BI_API_ENDPOINT
              value: http://control-cip:8080
            - name: BI_DATA_ENDPOINT
              value: http://data-cip:8080
            - name: US_MASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: datalens-secret
                  key: US_MASTER_TOKEN
          resources:
            requests:
              cpu: {{ .Values.application.resources.ui.requests.cpu }}
              memory: {{ .Values.application.resources.ui.requests.memory }}
            limits:
              cpu: {{ .Values.application.resources.ui.limits.cpu }}
              memory: {{ .Values.application.resources.ui.limits.memory }}